CREATE TABLE
  "Places" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "latitude" decimal(9, 6) NOT NULL,
    "longitude" decimal(9, 6) NOT NULL,
    "address" text,
    "approved" boolean NOT NULL,
    "created_by" integer,
    "created_timestamp" timestamp NOT NULL DEFAULT (current_timestamp)
  );

CREATE TABLE
  "AvailableUtilities" (
    "name" text PRIMARY KEY,
    "description" text NOT NULL
  );

CREATE TABLE
  "PlaceUtilities" (
    "place_id" integer,
    "utility_name" text,
    "description" text,
    PRIMARY KEY ("place_id", "utility_name")
  );

CREATE TABLE
  "AvailableCategories" ("name" text PRIMARY KEY, "description" text);

CREATE TABLE
  "PlaceCategories" (
    "place_id" integer,
    "category_name" text,
    "description" text,
    PRIMARY KEY ("place_id", "category_name")
  );

CREATE TABLE
  "Users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" text NOT NULL,
    "last_name" text NOT NULL,
    "email" text UNIQUE NOT NULL,
    "password_hash" text,
    "provider" text NOT NULL,
    "provider_id" text,
    "created_timestamp" timestamp NOT NULL DEFAULT (current_timestamp)
  );

CREATE TABLE
  "PlaceVisits" (
    "user_id" integer,
    "place_id" integer,
    "created_timestamp" timestamp NOT NULL DEFAULT (current_timestamp),
    PRIMARY KEY ("user_id", "place_id")
  );

CREATE TABLE
  "Reviews" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer,
    "place_id" integer NOT NULL,
    "rating" integer NOT NULL,
    "comment" text NOT NULL,
    "created_timestamp" timestamp NOT NULL DEFAULT (current_timestamp)
  );

CREATE TABLE
  "Wishlist" (
    "user_id" integer,
    "place_id" integer,
    PRIMARY KEY ("user_id", "place_id")
  );

CREATE TABLE
  "Friends" (
    "sender_id" integer,
    "receiver_id" integer,
    "confirmed" boolean NOT NULL,
    "time_sent" timestamp NOT NULL,
    "time_confirmed" timestamp,
    PRIMARY KEY ("sender_id", "receiver_id")
  );

CREATE TABLE
  "Images" (
    "place_id" integer NOT NULL,
    "filename" text PRIMARY KEY
  );

COMMENT ON COLUMN "Places"."created_by" IS 'Can be null due to deleted users';

COMMENT ON COLUMN "Users"."provider" IS 'Name of the sign in-method. for example ''google''. If the user is registered using email/pwd, this shall be ''local''';

COMMENT ON COLUMN "Users"."provider_id" IS 'Id from the provider, for example a Google user id if the user is registered via Google.';

COMMENT ON COLUMN "Reviews"."user_id" IS 'Can be null due to deleted users';

COMMENT ON COLUMN "Reviews"."rating" IS '1-5';

ALTER TABLE "PlaceUtilities" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");

ALTER TABLE "PlaceUtilities" ADD FOREIGN KEY ("utility_name") REFERENCES "AvailableUtilities" ("name");

ALTER TABLE "PlaceCategories" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");

ALTER TABLE "PlaceCategories" ADD FOREIGN KEY ("category_name") REFERENCES "AvailableCategories" ("name");

ALTER TABLE "PlaceVisits" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "PlaceVisits" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");

ALTER TABLE "Wishlist" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Wishlist" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");

ALTER TABLE "Friends" ADD FOREIGN KEY ("sender_id") REFERENCES "Users" ("id");

ALTER TABLE "Friends" ADD FOREIGN KEY ("receiver_id") REFERENCES "Users" ("id");

ALTER TABLE "Images" ADD FOREIGN KEY ("place_id") REFERENCES "Places" ("id");